apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexusHelm.fullname" . }}
  labels:
    {{- include "nexusHelm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nexusHelm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nexusHelm.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: nexus
        persistentVolumeClaim:
          claimName: {{.Values.persistence.pvcName}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nexusHelm.serviceAccountName" . }}
      securityContext:
        runAsUser: {{.Values.runAsUser}}
      containers:
        - name: nexus
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "sonatype/{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: "/nexus-data"
              name: nexus
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
